### ISSUE TITLE
Purpose of the Camera-Robot calibration 

### ISSUE THREAD

**Issue by mouhammad-abomoharam** [samarth-robo/blog#20]
Thanks for your this blog post:
[Post](https://samarth-robo.github.io/blog/2020/11/18/robot_camera_calibration.html)

﻿
﻿I have one general question regarding the purpose of this calibration for 2D cameras though.

﻿When using a normal 2D RGB Camera and after figuring out the camera position with respect to the robot base, how could one use this info to transform an arbitrary point in the camera image to the robot base coordinate system, so that the robot can for example move to this point.
﻿In my understanding, we need the depth information of this particular point to achieve that, but the 2D Camera doesn't give this. So we can't use the information from the camera to control the robot even if we calibrated both of them. Or am I missing something??

**Comment by samarth-robo** [comment]
Hi @mouhammad-abomoharam I made this a comment under the blog post, please see http://disq.us/p/30bk7xd.
